### ISSUE TITLE
Crash acontece por não encontrar pasta

### ISSUE THREAD

**Issue by JhowDroid** [davidsantos-br/ETS2Sync-Helper-2#1]
Sistema está apresentando problema quando não encontra a pasta do Euro Truck Simulator 2 nos documentos do usuário.
![8bb658dabb5a4ca29ea8bdd9b17ade96](https://cloud.githubusercontent.com/assets/18404916/16337621/3fa296d2-39ed-11e6-802e-66f08a371260.png)
Quando a pasta realmente não existe o aplicativo crasha e não termina o carregamento.
Considere tratar a mensagem no momento do crash e permitir que o usuário possa selecionar a pasta manualmente.
Entendemos que seria um padrão a pasta sempre estar localizada em "%USERPROFILE%\Documents\Euro Truck Simulator 2\", porém podem haver algumas exceções desconhecidas e a aplicação precisa estar preparada para estes casos.

**Comment by DaviMedrade** [comment]
Ooops. Closed the wrong issue.
