### ISSUE TITLE
Verificação de versão aparentemente com falha

### ISSUE THREAD

**Issue by JhowDroid** [davidsantos-br/ETS2Sync-Helper-2#10]
Ao abrir a versão que eu tinha localmente que era a 3.1.2 o sistema me informava que ele estava atualizado. Mas já existia a versão 3.1.3.

Sabe o que pode estar acontecendo?

Segue screenshot tirada esta noite dia 29/06/16:
![screenshot_1](https://cloud.githubusercontent.com/assets/18404916/16474649/ed894b1e-3e4e-11e6-9527-050d1a8f1e39.png)
@davidsantos-br

**Comment by DaviMedrade** [comment]
Isso foi intencional. A versão 3.1.3 corrige apenas um bug que não tem a ver com a sincronização (cf. #5). Como a mudança é pequena, a sincronização funciona, e hoje ou amanhã vai ter outra atualização, eu preferi não incomodar os usuários com a mensagem de atualização por enquanto.

Na próxima versão, inclusive, atualizações podem ser de dois tipos: se for uma atualização pequena, o programa vai mostrar no rodapé que tem versão nova mas não vai perguntar se a pessoa quer atualizar sempre que abrir o programa; essa mensagem mais invasiva vai ser usada só para atualizações maiores (i.e. atualizações que corrigem bugs importantes ou adicionam novas funcionalidades).
