### ISSUE TITLE
sugestão para um "change_lang"

### ISSUE THREAD

**Issue by JhowDroid** [davidsantos-br/ETS2Sync-Helper-2#4]
Acredito que você já deva ter pensado nisso. Mas este ticket é para reforçar e lembrar.
Ao invés de termos arquivos diferentes para baixar que funcionam com linguagens diferentes como é o cenário atual, poderíamos ter um único pacote para baixar e um mecanismo dentro do app para mudar a linguagem sempre que quiser. Esta opção pode estar no topo direito da aplicação como um dropdown por exemplo.

**Comment by DaviMedrade** [comment]
Isso provavelmente vai ser implementado logo logo. Atualmente o que preciso pra isso, do ponto de vista de _user experience_, é uma forma de lembrar o idioma selecionado quando o programa for aberto novamente. Isso é simples de implementar, e já vai ter que ser implementado quando for adicionado o suporte para o ATS (para que o usuário não tenha que ficar selecionando qual jogo quer sincronizar cada vez que abrir o programa).

**Comment by DaviMedrade** [comment]
Se tudo correr bem, a versão com todos os idiomas no mesmo executável deve estar pronta amanhã.

**Comment by DaviMedrade** [comment]
Done. Started @ c5be8c966962bc14eee92411b06ce8497f4f9c70.
