### ISSUE TITLE
Erro ao abrir a URL para baixar versão nova

### ISSUE THREAD

**Issue by DaviMedrade** [davidsantos-br/ETS2Sync-Helper-2#5]
No Windows 10 causa um erro quando o programa tentar abrir o navegador para atualização. Estou testando a versão 3.1.1 e ele tentou atualizar para a atual 3.1.2. Erro: Undefined method `encoding' for URI::HTTP.

(@trev0rbr)

**Comment by DaviMedrade** [comment]
Ooops. Vou resolver isso hoje mais tarde (apesar que não vai dar pra atualizar pela mensagem do programa…) :frowning:

**Comment by j1m1l0k0** [comment]
Não tem uma forma de vc usar o http para fazer um GET ?  eu não conheço a programação via ruby mais acredito que tenha como fazer o script atualizar internamente ao invés de abrir o navegador.
ou usando uma lib do libcurl será que tem portado pra ruby ? Vou dar uma pesquisada.. .de repente consigo te ajudar de alguma forma.

**Comment by DaviMedrade** [comment]
Quanto ao programa atualizar a si mesmo, veja #2.
