### ISSUE TITLE
Atualizador do programa ETS2Sync-Helper-2

### ISSUE THREAD

**Issue by j1m1l0k0** [davidsantos-br/ETS2Sync-Helper-2#9]
David, fiz um atualizador para o seu programa e estou testando no momento.

https://github.com/trev0rbr/ETS2Sync-Helper-2/blob/master/update.dat esse arquivo é onde ficará as informações do programa atualizado.

**Comment by DaviMedrade** [comment]
Eu pretendo adicionar essa funcionalidade no próprio programa, então não sei se será realmente necessário a menos que seja isso que você tenha feito.

**Comment by j1m1l0k0** [comment]
@davidsantos-br Eu fiz um externo, mais é melhor deixar como está atualmente se vai implementar a rotina internamente no sistema o meu não terá uso.  Mais valeu de qualquer forma ehehe

**Comment by DaviMedrade** [comment]
Discussão futura a esse respeito pode ficar em #2 para evitar duplicação.
